version: 0.0
os: linux

files:
  - source: ./__SERVICE_NAME__.jar
    destination: __DEPLOY_DIR__

hooks:
  BeforeInstall:
    - location: ./before-install.sh
      timeout: 20
  ApplicationStart:
    - location: ./application-start.sh
      timeout: 40
  ValidateService:
    - location: ./validate-service.sh
      timeout: 40
